export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = " USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_OPCEN_ADMIN = "USER_OPCEN_ADMIN";
export const LOGOUT = "LOGOUT";
// PROFILES
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const GET_PROFILES = "GET_PROFILES";

export const GET_REPOS = "GET_REPOS";
export const GET_POSTS = "GET_POSTS";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const DELETE_POST = "DELETE_POST";
export const ADD_POST = "ADD_POST";
export const GET_POST = "GET_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const USER_DOEST_EXIST = "USER_DOEST_EXIST";

export const GET_POST_IMAGE = "GET_POST_IMAGE";
export const POST_IMG_ERROR = "POST_IMG_ERROR";
// Map Actions
export const GET_COMPLETE_ADDRESS = "GET_COMPLETE_ADDRESS";
export const GET_AREA = "GET_AREA";
export const GET_CITY = "GET_CITY";
export const GET_STATE = "GET_STATE";
export const GET_COUNTRY = "GET_COUNTRY";
export const MAP_LOCATE = "MAP_LOCATE";
export const MAP_SEARCH = "MAP_SEARCH";

// SMS/OTP/ Update Password

export const SEND_OTP = "SEND_OTP";
export const SEND_OTP_FAIL = "SEND_OTP_FAIL";
export const REMOVE_OTP = "REMOVE_OTP";
export const OTP_MATCH = "OTP_MATCH";
export const OTP_NOT_MATCH = "OTP_NOT_MATCH";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

// OPCEN
export const CREATE_OPCEN = "CREATE_OPCEN";
export const ERROR_CREATE_OPCEN = "ERROR_CREATE_OPCEN";
export const OPCEN_REGISTER_SUCCESS = "OPCEN_REGISTER_SUCCESS";
export const OPCEN_REGISTER_FAIL = "OPCEN_REGISTER_FAIL";
export const GET_OPCENS = "GET_OPCENS";
export const GET_OPCENS_FAIL = "GET_OPCENS_FAIL";
export const GET_OPCEN = "GET_OPCEN";
export const GET_OPCEN_FAIL = "GET_OPCEN_FAIL";

// OPCEN PROFILE

export const GET_OPCEN_PROFILE = "GET_OPCEN_PROFILE";
export const PROFILE_OPCEN_ERROR = "PROFILE_OPCEN_ERROR";
export const CLEAR_OPCEN_PROFILE = "CLEAR_OPCEN_PROFILE";
export const UPDATE_OPCEN_PROFILE = "UPDATE_OPCEN_PROFILE";
export const ACCOUNT_OPCEN_DELETED = "ACCOUNT_OPCEN_DELETED";
export const GET_OPCEN_PROFILES = "GET_OPCEN_PROFILES";

// INCIDENTS
export const CREATE_INCIDENT = "CREATE_INCIDENT";
export const ERROR_CREATE_INCIDENT = "ERROR_CREATE_INCIDENT";
export const INCIDENT_SUMMIT_SUCCESS = "INCIDENT_SUMMIT_SUCCESS";
export const INCIDENT_SUMMIT_FAIL = "INCIDENT_SUMMIT_FAIL";
export const GET_INCIDENT = "GET_INCIDENT";
export const GET_INCIDENT_FAIL = "GET_INCIDENT_FAIL";
export const GET_INCIDENTS = "GET_INCIDENTS";
export const GET_INCIDENTS_FAIL = "GET_INCIDENTS_FAIL";
